"""initial_schema

Revision ID: 4369c7de9f8d
Revises: 
Create Date: 2026-03-24 16:51:50.135447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4369c7de9f8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('source_excel_filename', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_campaigns_name')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaigns_date_range', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_campaigns_status', ['status'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_city', ['city'], unique=False)
        batch_op.create_index('ix_customers_full_name', ['full_name'], unique=False)
        batch_op.create_index('ix_customers_phone', ['phone'], unique=False)

    op.create_table('import_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.Enum('CAMPAIGN_PRICE_LIST', 'MASTER_PRICE_LIST', 'CUSTOMER_HISTORY', name='importtype'), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'COMPLETED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_successful', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_import_sessions_status', ['status'], unique=False)
        batch_op.create_index('ix_import_sessions_type', ['import_type'], unique=False)

    op.create_table('price_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_price_lists_name')
    )
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.create_index('ix_price_lists_name', ['name'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_brand', ['brand'], unique=False)
        batch_op.create_index('ix_products_brand_normalized_name', ['brand', 'normalized_name'], unique=False)
        batch_op.create_index('ix_products_model', ['model'], unique=False)
        batch_op.create_index('ix_products_name', ['name'], unique=False)
        batch_op.create_index('ix_products_normalized_name', ['normalized_name'], unique=False)
        batch_op.create_index('ix_products_supplier_code', ['supplier_code'], unique=False)

    op.create_table('campaign_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('regular_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('status_label', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('discount_price IS NULL OR discount_price >= 0', name='ck_campaign_prices_discount_price'),
    sa.CheckConstraint('points IS NULL OR points >= 0', name='ck_campaign_prices_points'),
    sa.CheckConstraint('regular_price >= 0', name='ck_campaign_prices_regular_price'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'product_id', name='uq_campaign_product')
    )
    op.create_table('import_error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('excel_row_number', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['import_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_error_logs', schema=None) as batch_op:
        batch_op.create_index('ix_import_error_logs_session_id', ['session_id'], unique=False)

    op.create_table('import_product_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('excel_row_number', sa.Integer(), nullable=True),
    sa.Column('raw_supplier_code', sa.String(length=100), nullable=True),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('raw_normalized_name', sa.String(length=255), nullable=False),
    sa.Column('raw_brand', sa.String(length=120), nullable=True),
    sa.Column('match_source', sa.Enum('SUPPLIER_CODE', 'NORMALIZED_NAME', 'NORMALIZED_NAME_AND_BRAND', 'MANUAL', 'NEW_PRODUCT', name='productmatchsource'), nullable=False),
    sa.Column('confidence_note', sa.Text(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['import_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_product_matches', schema=None) as batch_op:
        batch_op.create_index('ix_import_product_matches_match_source', ['match_source'], unique=False)
        batch_op.create_index('ix_import_product_matches_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_import_product_matches_session_id', ['session_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('product_normalized_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('product_code_snapshot', sa.String(length=100), nullable=True),
    sa.Column('product_brand_snapshot', sa.String(length=120), nullable=True),
    sa.Column('product_model_snapshot', sa.String(length=150), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('installments_count', sa.Integer(), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=True),
    sa.Column('contract_number', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('installments_count >= 1 AND installments_count <= 10', name='ck_orders_installments_count'),
    sa.CheckConstraint('quantity > 0', name='ck_orders_quantity'),
    sa.CheckConstraint('total_price_snapshot >= 0', name='ck_orders_total_price_snapshot'),
    sa.CheckConstraint('unit_price_snapshot >= 0', name='ck_orders_unit_price_snapshot'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_campaign_id', ['campaign_id'], unique=False)
        batch_op.create_index('ix_orders_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_orders_order_date', ['order_date'], unique=False)
        batch_op.create_index('ix_orders_status', ['status'], unique=False)

    op.create_table('price_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('supplier_code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('regular_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.create_index('ix_price_list_items_brand', ['brand'], unique=False)
        batch_op.create_index('ix_price_list_items_name', ['name'], unique=False)
        batch_op.create_index('ix_price_list_items_price_list_id', ['price_list_id'], unique=False)
        batch_op.create_index('ix_price_list_items_supplier', ['supplier'], unique=False)

    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='installmentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_installments_amount'),
    sa.CheckConstraint('installment_number >= 1', name='ck_installments_number'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'installment_number', name='uq_order_installment_number')
    )
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.create_index('ix_installments_due_date', ['due_date'], unique=False)
        batch_op.create_index('ix_installments_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_installments_status', ['status'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_installment_id', ['installment_id'], unique=False)
        batch_op.create_index('ix_payments_payment_date', ['payment_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_payment_date')
        batch_op.drop_index('ix_payments_installment_id')

    op.drop_table('payments')
    with op.batch_alter_table('installments', schema=None) as batch_op:
        batch_op.drop_index('ix_installments_status')
        batch_op.drop_index('ix_installments_order_id')
        batch_op.drop_index('ix_installments_due_date')

    op.drop_table('installments')
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.drop_index('ix_price_list_items_supplier')
        batch_op.drop_index('ix_price_list_items_price_list_id')
        batch_op.drop_index('ix_price_list_items_name')
        batch_op.drop_index('ix_price_list_items_brand')

    op.drop_table('price_list_items')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_status')
        batch_op.drop_index('ix_orders_order_date')
        batch_op.drop_index('ix_orders_customer_id')
        batch_op.drop_index('ix_orders_campaign_id')

    op.drop_table('orders')
    with op.batch_alter_table('import_product_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_import_product_matches_session_id')
        batch_op.drop_index('ix_import_product_matches_product_id')
        batch_op.drop_index('ix_import_product_matches_match_source')

    op.drop_table('import_product_matches')
    with op.batch_alter_table('import_error_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_import_error_logs_session_id')

    op.drop_table('import_error_logs')
    op.drop_table('campaign_prices')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_supplier_code')
        batch_op.drop_index('ix_products_normalized_name')
        batch_op.drop_index('ix_products_name')
        batch_op.drop_index('ix_products_model')
        batch_op.drop_index('ix_products_brand_normalized_name')
        batch_op.drop_index('ix_products_brand')

    op.drop_table('products')
    with op.batch_alter_table('price_lists', schema=None) as batch_op:
        batch_op.drop_index('ix_price_lists_name')

    op.drop_table('price_lists')
    with op.batch_alter_table('import_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_import_sessions_type')
        batch_op.drop_index('ix_import_sessions_status')

    op.drop_table('import_sessions')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_phone')
        batch_op.drop_index('ix_customers_full_name')
        batch_op.drop_index('ix_customers_city')

    op.drop_table('customers')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_status')
        batch_op.drop_index('ix_campaigns_date_range')

    op.drop_table('campaigns')
    # ### end Alembic commands ###
